version: '3'

services:
  web: &app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      EDITOR: vi
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379
      WEBPACKER_DEV_SERVER_HOST: webpacker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  sidekiq:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      EDITOR: vi
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    tty: true
    stdin_open: true
  redis:
    image: redis:6.2.7
    volumes:
      - "redis_volume:/data"
    command: redis-server --appendonly yes
  webpacker:
    <<: *app
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_volume:
  redis_volume:

